### ISSUE TITLE
iyes_loopless support

### ISSUE THREAD

**Issue by inodentry** [Leafwing-Studios/leafwing_input_manager#104]
Optional cargo dependency. If enabled, provide APIs to use `iyes_loopless` states in addition to Bevy states.

**Comment by alice-i-cecile** [comment]
I think we should be able to get this nicely with #105 :) I don't even think we'll need an optional dependency, but I would like to demo it in an example (using a dev-dependency).

**Comment by alice-i-cecile** [comment]
Solved by #105.
