### ISSUE TITLE
Add comparison with other bevy input crates

### ISSUE THREAD

**Issue by johanhelsing** [Leafwing-Studios/leafwing_input_manager#130]
## What problem did the developer encounter?

As someone new to this and other bevy input crates, it's hard to tell from just the list of feature why I should choose one crate over the other.

## How could this be better documented?

I realize this crate is still a work in progress, but it would be nice to have a table or something in the readme with checkmarks/xes on the things that this crate supports and other input crates don't and vice-versa.

e.g.

||`leafwing_input_manager`|`bevy_input_actionmap`|
|-|-|-|
|analog axis input|❌|✅|
|mocking api|✅|❌|
|chords|✅|❌|
|arpeggios|❌|❌|

note: I don't know if the above is correct, just wanted to illustrate the idea.

**Comment by alice-i-cecile** [comment]
I'm uncomfortable about doing so; this feels like a form of bragging in a collaborative space.
