### ISSUE TITLE
Inputs ignored if using bevy::input::InputPlugin

### ISSUE THREAD

**Issue by ramirezmike** [Leafwing-Studios/leafwing_input_manager#71]
## Version

de284e51dfc4f2bb611a75da3e41d1b79fb2cbb3

## Operating system & version

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

## What you did
Running the single_player example

## What you expected to happen

Keyboard keys/Gamepad presses would be detected

## What actually happened

Input is not detectedd

## Additional information

Adding the bevy::input::InputPlugin plugin causes issues detecting key presses/gamepad presses. Using the single_player example, if you comment out the add_plugin(bevy::input::InputPlugin) line, the keypresses are detected (Q and Space) but running the example as-is won't show any keypress-detection output.

Additionally, the single_player example has an EventWriter example to show detecting arrow-keys and creating events, but it doesn't have an EventReader that outputs the keypresses which also tripped me up initially.

Finally: all this said, I don't see a real reason to import the InputPlugin if you're using this crate :man_shrugging:

**Comment by alice-i-cecile** [comment]
Fixed :)
