### ISSUE TITLE
Treat modifiers as modifiers and not keys

### ISSUE THREAD

**Issue by johanhelsing** [Leafwing-Studios/leafwing_input_manager#72]
## What problem does this solve?

Detect Ctrl+F, but not F+Ctrl

## What solution would you like?

Perhaps something like this?

```rust
input_map.insert_with_modifiers(Find, [LControl, LAlt], F);
```

## Related work

Chords are similar, but they trigger when F is held first and then Ctrl is tapped.

**Comment by alice-i-cecile** [comment]
Yep, this is the feature I've been calling "arpeggios".

**Comment by alice-i-cecile** [comment]
Closing as a duplicate of #49.
