### ISSUE TITLE
Resolve button conflicts

### ISSUE THREAD

**Issue by Dekakaruk** [Leafwing-Studios/leafwing_input_manager#73]
Let's assume we have input attached to two entities, one has mapped a chord [ctrl, a], and the other just [a]. If ctrl-a is pressed, the common sense response would be only to run the first action, but in this plugin both are run. 

The problem seems to be already solved in alternative crates, e.g. https://github.com/lightsoutgames/bevy_input_actionmap, would be nice to have it here too.

**Comment by alice-i-cecile** [comment]
Yep, this is "clashes". It will be fixed in the next release :)

**Comment by alice-i-cecile** [comment]
Done as part of #67.
