### ISSUE TITLE
in combination with bevy_editor_pls it causes panic when game paused

### ISSUE THREAD

**Issue by SET001** [Leafwing-Studios/leafwing_input_manager#74]
## Version
0.2.0

## Operating system & version

Ubuntu 18.04

## What you did

use [leafwing_input_manager](https://github.com/Leafwing-Studios/leafwing_input_manager) with [bevy_editor_pls](https://github.com/jakobhellermann/bevy_editor_pls)
run game
open bevy_editor_pls UI and pause game

## What you expected to happen

game should pause and unpause without panicks

## What actually happened
app panicked with the message:
```
thread 'Compute Task Pool (0)' panicked at 'The `Time` resource has never been updated!', /home/set/.cargo/registry/src/github.com-1ecc6299db9ec823/leafwing-input-manager-0.2.0/src/systems.rs:20:18
```

## Additional information
I'm not sure should this be investigated here or on bevy_editor_pls side
here is a minimum gist that reproduces the problem https://gist.github.com/SET001/577880375132b6ebd76196af14f8e174

**Comment by alice-i-cecile** [comment]
Fixed by #146 :D
