### ISSUE TITLE
Create API to return which UserInput triggered an Action

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing_input_manager#76]
## What problem does this solve?

Figure out why an action was triggered.

This is useful for debugging, but also for getting analog values (alternative to #60).

## What solution would you like?

Create a `triggering_inputs(action: A) -> Vec<UserInput>` method on `ActionState` that returns the `UserInput` that triggered the action.

**Comment by alice-i-cecile** [comment]
Should probably be a `SmallVec`, per #77.

**Comment by plof27** [comment]
This feature is finished being built as of https://github.com/Leafwing-Studios/leafwing_input_manager/commit/2ec61b035ddcca95d45669fa200458dd55d0519d but it still needs tests and examples

**Comment by alice-i-cecile** [comment]
Done as part of #67.
