### ISSUE TITLE
Turn input_mocking into a feature

### ISSUE THREAD

**Issue by Shatur** [Leafwing-Studios/leafwing_input_manager#80]
## What problem does this solve?

Currently `leafwing_input_manager` depends on `bevy_ui` because of the `input_mocking` module.

## What solution would you like?

I see several options:

1. Turn `input_mocking` into a feature.
2. Move `input_mocking` into a separate plugin.
3. Add a feature that disables `bevy_ui` dependency for `input_mocking`

Currently used `render` feature is a [group](
https://github.com/bevyengine/bevy/blob/a291b5aaedb4affcb31df2e2e63cb0c665ffb24a/Cargo.toml#L35-L43) that contains unneeded stuff, like `bevy_ui` or `bevy_text`. I was about to submit a PR but noticed that `bevy_ui` is a required dependency for this plugin.

**Comment by alice-i-cecile** [comment]
> Move input_mocking into a separate plugin.

Long term, I think this probably belongs upstream in `bevy_input`. For now though, we can make this a feature. 

If you're interested, I would welcome a PR to the `dev` branch @Shatur. We should also split out the `bevy_ui` interaction handling into a separate feature as well.

**Comment by Shatur** [comment]
> Long term, I think this probably belongs upstream in bevy_input. 

It would be great!

> We should also split out the bevy_ui interaction handling into a separate feature as well.

@alice-i-cecile just noticed that `bevy_ui` used not only in `input_mocking` module. I think that even `bevy_ui` separation is enough. I opened #82.

**Comment by Shatur** [comment]
Closed by #82.
