### ISSUE TITLE
Move clashing settings from InputMap into a resource

### ISSUE THREAD

**Issue by Shatur** [Leafwing-Studios/leafwing_input_manager#94]
## What problem does this solve?

I trying to serialize InputMap to save it as settings or send over a network. And clashing settings will be serialized as well.

## What solution would you like?

Move clashing settings into a resource since it's weird to configure it per-player basis. And turn clashing inputs into a separate component that will be updated in a system on each `InputMap` change (this will be even more efficient doing it each insertion).

**Comment by alice-i-cecile** [comment]
Done.
